[package]
name = "evm"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18"
gfx_device_gl = "0.16"
glutin = "0.26"
image = "0.23"
imgui = "0.7.0"
clipboard = "0.5"

sdl2 = { version = "0.34", features = ["bundled"] }
gl = "0.10.0"
imgui-sdl2 = "0.14.0"
imgui-opengl-renderer = "0.11.0"